### PR TITLE
Drop debian packaging files

### PR DESCRIPTION
**Pull request by rbalint**
Also recommend installing esnacc from official Debian package

I have uploaded the package to Debian and it is waiting from FTP Master
approval:
https://ftp-master.debian.org/new/esnacc_1.8.0-1.html

### CODE REVIEW

**Comment by orgcandman** [comment]
I have no problems applying this - please post it to the mailing list (dev@lists.esnacc.org); there are a couple of folks who can't participate on github, and might want to make some input.

I have two questions - I suspect I know the answers, but just want to confirm:

1) Do you want this backported to branch-1.8 as well?

2) Would you be okay with renaming the debian/ directory and keeping the ability to build `deb` packages from the repository?  I kindof like the convenience, but I understand if you wouldn't want that.

**Comment by rbalint** [comment]
@orgcandman There is a good upstream guide at https://wiki.debian.org/UpstreamGuide#Initial_Packaging 
If you would like to keep the debian/ dir it is OK, but please don't include it in the release tarball.

Backporting is not badly needed, but I have already filtered the directory from the package's original tarball - but I forgot renaming the version to ...+dfsg1 :-(.

If you would like to keep the directory please consider syncing the content with latest package version at Debian.

**Comment by rbalint** [comment]
@orgcandman While I can live with that sending patches to both GitHub and a mailing list is a bit of a burden for contributors. Maybe automatically forwarding GitHub PR-s would provide a more pleasant experience.

**Comment by orgcandman** [comment]
I will look into it - for now sending patches to dev@lists.esnacc.org should be good enough; the other project committer rarely checks github.
Meanwhile, I'm going to merge your patch, and will close this when I finish.
Thanks so much for your contributions, @rbalint

**Comment by orgcandman** [comment]
I've applied your patch, and will make sure that the release process removes the debian/ directory before bundling.  Thanks again for your work.

**Pull request closed without merging**
