### PR TITLE
Use const pointer rather than casting to non-const

### PR DESCRIPTION
**Pull request by vegarwe**

### CODE REVIEW

**Comment by orgcandman** [comment]
Can I get your "Signed-off-by: ..." tag for this?

**Comment by vegarwe** [comment]
@orgcandman Not sure what you mean by 'get your "Signed-off-by:" tag'. Was it meant for me? Just tell me what you want me to do.

**Comment by orgcandman** [comment]
Sorry for the confusion.  We use what's called Developer Certificate of Origin, or DCO. Every patch submitted needs to have some number of tags (in the form of text at the end of the commit message) associated. It's described in CONTRIBUTING.md, but I'll paste the relevant excerpt here.

Developer's Certificate of Origin

To help track the author of a patch as well as the submission chain, and be clear that the developer has authority to submit a patch for inclusion in Enhanced SNACC please sign off your work. The sign off certifies the following:

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Patch Signing Tags

The Signed-off-by tag indicates that you were directly involved in the generation of this patch, either by producing the code, or by influencing it heavily. Signing off on a change indicates that you take direct responsibility for that change.

The Acked-by tag indicates that you acknowledge the change. It indicates that you have read the change, understood it, and believe it to be acceptable for inclusion in the development tree. Acknowledgement usually implies that you have done a cursory build with the patch. The Reviewed-by tag means is the same as the Acked-by but does not imply you have built the change.

The Tested-by tag indicates anyone who has applied the code change to their tree, compiled with the change, and executed the functionality being manipulated.

The Reported-by tag indicates a user that was responsible for reporting a bug in the code.

**Comment by orgcandman** [comment]
I've added your signoff tag to the commits, and put you into the authors file.  If this is inappropriate, please re-open this request, and we can back out the changes.

**Pull request closed without merging**
